--- 
excluded_pkgfiles: []

project_pubdir: /usr/local/www/public/code/
project_pubhost: deveiate.org
project_homepage: http://deveiate.org/drbservice.html
project_requirements: 
  drb: ">=0"
release_smtphost: mail.faeriemud.org
project_description: |-
  DRbservice provides a framework for creating a DRb service that uses an SSL-encrypted channel
  and authentication with a minimum of effort, along with a tool that can easily set up the
  service in an environment intended to be run via one of several different deployment strategies.
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: 
  trollop: ">=1.15"
project_summary: A tool for easing the creation of SSL-encrypted, authenticated DRb services.
version_file: drbservice.rb
additional_pkgfiles: []

dev_dependencies: {}

authors: 
  Michael Granger: ged@FaerieMUD.org
post_install_message: " \n\
  To get started, run 'drbservice <name of service>'\n "
project_name: drbservice
